Refactor/parse comment line
onlydustxyz/kaaper pull request #26
Opened 2022-07-29 16:30 UTC by internnos

2022-08-01 08:40 UTC, AnthonyBuisset requested changes

2022-08-01 08:40 UTC, AnthonyBuisset commented on src/lib/parser/function-comment/desc.ts
> +      const regexp = /#(\s+)(.+)/gm;
I see a lot of duplicate code, can you please refactor into smaller functions and give proper name to understand what the code is doing ?
It is a bit difficult to follow right now

2022-08-01 10:40 UTC, internnos commented on src/lib/parser/function-comment/desc.ts
> +      const regexp = /#(\s+)(.+)/gm;
gotcha!

will try to give proper name and comments for those tests

2022-08-01 12:18 UTC, internnos commented on src/lib/parser/function-comment/desc.ts
> +      const regexp = /#(\s+)(.+)/gm;
I think that tests in `test\suite\function-comment` can be removed, since it have been covered in `cairo-parser/getScopeParsingResult`

and I will refactor the assertion functions so it is easier to read, understand, and navigate, plus the proper documentation

what do you think?

@AnthonyBuisset

2022-08-01 13:12 UTC, internnos commented on src/lib/parser/function-comment/desc.ts
> +      const regexp = /#(\s+)(.+)/gm;
i've made some refactoring for `getScopeParsingResult/event.test.ts`

any feedback?

thank you

@AnthonyBuisset

2022-08-01 18:42 UTC, internnos commented on src/lib/parser/function-comment/desc.ts
> +      const regexp = /#(\s+)(.+)/gm;
i've refactored this function

let me know if there are any feedback

thank you!

@AnthonyBuisset

2022-08-02 18:14 UTC, AnthonyBuisset approved these changes

2022-08-02 18:30 UTC, merged