Feat/function signature char index
onlydustxyz/kaaper pull request #27
Opened 2022-08-02 22:30 UTC by internnos

2022-08-04 12:15 UTC, AnthonyBuisset requested changes

2022-08-04 12:15 UTC, AnthonyBuisset commented on src/lib/parser/function-comment/desc.ts
> +  constructor(functionCommentText: string | null) {
why do we need this null option ?

2022-08-04 12:15 UTC, AnthonyBuisset commented on src/test/suite/cairo-parser/dumpParsingResult.test.ts
> +  test("should not get any comments in from library.cairo", () => {
where are the assertions in this test ?

2022-08-04 12:15 UTC, AnthonyBuisset commented on src/test/suite/cairo-parser/parseCommentLinesEmptyComment.test.ts
> +  //   test("Namespace: 1 ", () => {
please delete commented code

2022-08-04 14:34 UTC, internnos commented on src/test/suite/cairo-parser/parseCommentLinesEmptyComment.test.ts
> +  //   test("Namespace: 1 ", () => {
on it

2022-08-04 14:39 UTC, internnos commented on src/lib/parser/function-comment/desc.ts
> +  constructor(functionCommentText: string | null) {
because it would be easier to handle `non commented` function comments

let say there is this function scope

```
@event
func Approval(owner : felt, spender : felt, value : Uint256):
end
```

before this PR, the `getScopeParsingResult` would throw error since there there is a regex matching for the text

if it is null, it would be easy to handle, though, instead of giving "" for null value, which is less direct

2022-08-04 14:46 UTC, internnos commented on src/test/suite/cairo-parser/dumpParsingResult.test.ts
> +  test("should not get any comments in from library.cairo", () => {
oh yeah i should've added reference files to compare

on it!

2022-08-04 18:19 UTC, internnos commented on src/lib/parser/function-comment/desc.ts
> +  constructor(functionCommentText: string | null) {
do i need to change this @AnthonyBuisset? 

i think this is more like style preference, so if that's the case, i'm very open to change this into `string` instead of using `string|null`!

2022-08-05 10:49 UTC, AnthonyBuisset commented on src/lib/parser/function-comment/desc.ts
> +  constructor(functionCommentText: string | null) {
My concern is that if there is no comment to parse, we should not even instantiate a parser at all
i.e. the null check should be done at a higher level.
Also we should never have "" as comments as well, this would mean no comment, so no parser to be used.
What do you think ? Is it too big to refactor ?

2022-08-05 11:00 UTC, internnos commented on src/lib/parser/function-comment/desc.ts
> +  constructor(functionCommentText: string | null) {
aah gotcha!

understandable, but i think this is too big to refactor and this is out of scope. i guess this is more like enhancement instead of core functionality

i can open the issue if you're okay with this!

2022-08-05 11:27 UTC, AnthonyBuisset commented on src/lib/parser/function-comment/desc.ts
> +  constructor(functionCommentText: string | null) {
enhancements are part of the development lifecycle, refactoring should be happening on a regular basis to remove this kind of "code smell".
I agree to tackle this one in a dedicated PR/github issue. Can you please open it ?

2022-08-05 11:27 UTC, AnthonyBuisset submitted a review, later dismissed

2022-08-05 16:27 UTC, AnthonyBuisset approved these changes

2022-08-05 16:27 UTC, merged